/**
 * Intent Schema Module
 *
 * Pre-analyzes user requests before sandbox execution to provide:
 * - Prioritized KSA selection
 * - Structured goals and deliverables
 * - User-configurable policies
 *
 * Generated by a fast LLM (GROQ via OpenRouter) while the sandbox warms up.
 */

// Re-export types
export * from "./types";

// Re-export actions (will be added)
export * from "./generate";
