/**
 * Cloudflare CLI Commands
 *
 * Initialize and deploy Cloudflare workers and R2 buckets.
 */

import { $ } from "bun";

interface CloudflareOptions {
  project?: string;
}

/**
 * Initialize Cloudflare configuration.
 */
export async function initCloudflare(options: CloudflareOptions) {
  const projectDir = options.project || process.cwd();
  const workersDir = `${projectDir}/workers`;

  console.log("Initializing Cloudflare configuration...\n");

  // Create workers directory
  await $`mkdir -p ${workersDir}/frames/src`;

  // Create wrangler.toml for frames worker
  const wranglerToml = `name = "lakitu-frames"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "FRAMES_BUCKET"
bucket_name = "frames"
preview_bucket_name = "frames-preview"

[build]
command = "bun install"
`;

  await Bun.write(`${workersDir}/frames/wrangler.toml`, wranglerToml);

  // Create package.json
  const packageJson = {
    name: "lakitu-frames-worker",
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "wrangler dev",
      deploy: "wrangler deploy",
    },
    devDependencies: {
      wrangler: "^3.0.0",
      "@cloudflare/workers-types": "^4.0.0",
    },
  };

  await Bun.write(`${workersDir}/frames/package.json`, JSON.stringify(packageJson, null, 2));

  // Create worker entry point
  const workerCode = `/**
 * Frames Worker - Serves static sites from R2
 *
 * Generated by @lakitu/sdk
 */

import { createFramesHandler } from "@lakitu/sdk/cloudflare/workers/frames";

export interface Env {
  FRAMES_BUCKET: R2Bucket;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const handler = createFramesHandler(env);
    return handler(request);
  },
};
`;

  await Bun.write(`${workersDir}/frames/src/index.ts`, workerCode);

  console.log("Created Cloudflare worker configuration:");
  console.log(`  - ${workersDir}/frames/wrangler.toml`);
  console.log(`  - ${workersDir}/frames/package.json`);
  console.log(`  - ${workersDir}/frames/src/index.ts`);
  console.log("\nNext steps:");
  console.log("  1. Install dependencies: cd workers/frames && bun install");
  console.log("  2. Configure R2 bucket in Cloudflare dashboard");
  console.log("  3. Deploy: wrangler deploy");
}

/**
 * Deploy Cloudflare workers.
 */
export async function deployCloudflare(options: CloudflareOptions) {
  const projectDir = options.project || process.cwd();
  const workersDir = `${projectDir}/workers`;

  console.log("Deploying Cloudflare workers...\n");

  // Check if wrangler is installed
  try {
    await $`which wrangler`.quiet();
  } catch {
    console.error("Error: wrangler CLI not found. Install with: npm install -g wrangler");
    process.exit(1);
  }

  // Deploy frames worker
  const framesDir = `${workersDir}/frames`;
  try {
    await $`test -f ${framesDir}/wrangler.toml`.quiet();
  } catch {
    console.error(`Error: No wrangler.toml found in ${framesDir}`);
    console.error("Run 'npx @lakitu/sdk cloudflare init' first");
    process.exit(1);
  }

  console.log("Deploying frames worker...");
  const result = await $`cd ${framesDir} && wrangler deploy`.nothrow();

  if (result.exitCode === 0) {
    console.log("\n✅ Frames worker deployed successfully!");
  } else {
    console.error("\n❌ Deployment failed:", result.stderr.toString());
    process.exit(1);
  }
}

/**
 * Main cloudflare command handler.
 */
export async function cloudflare(subcommand: string, options: CloudflareOptions) {
  switch (subcommand) {
    case "init":
      await initCloudflare(options);
      break;
    case "deploy":
      await deployCloudflare(options);
      break;
    default:
      console.log("Usage: lakitu cloudflare <init|deploy>");
      console.log("\nCommands:");
      console.log("  init    Initialize Cloudflare worker configuration");
      console.log("  deploy  Deploy workers to Cloudflare");
  }
}
